# GitHub Labels Configuration
# Use with: https://github.com/marketplace/actions/github-labeler

labels:
  # Type labels
  - name: bug
    color: d73a4a
    description: Something isn't working
  
  - name: enhancement
    color: a2eeef
    description: New feature or request
  
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  
  - name: security
    color: ee0701
    description: Security related issue
  
  # Component labels
  - name: face-recognition
    color: 7057ff
    description: Face recognition related
  
  - name: database
    color: 0e8a16
    description: Database related
  
  - name: api
    color: 1d76db
    description: API endpoints
  
  - name: ui
    color: fbca04
    description: User interface related
  
  - name: frontend
    color: fef2c0
    description: Frontend code (HTML/CSS/JS)
  
  - name: python
    color: 3572A5
    description: Python code
  
  - name: tests
    color: bfd4f2
    description: Test related
  
  - name: configuration
    color: d4c5f9
    description: Configuration files
  
  - name: ci/cd
    color: 5319e7
    description: CI/CD pipeline related
  
  # Priority labels
  - name: "priority: high"
    color: b60205
    description: High priority
  
  - name: "priority: medium"
    color: fbca04
    description: Medium priority
  
  - name: "priority: low"
    color: 0e8a16
    description: Low priority
  
  # Size labels
  - name: "size: XS"
    color: 3CBF00
    description: Extra small change (<10 lines)
  
  - name: "size: S"
    color: 5D9801
    description: Small change (<50 lines)
  
  - name: "size: M"
    color: 7F7203
    description: Medium change (<200 lines)
  
  - name: "size: L"
    color: A14C05
    description: Large change (<500 lines)
  
  - name: "size: XL"
    color: C32607
    description: Extra large change (500+ lines)
  
  # Status labels
  - name: "status: in progress"
    color: ededed
    description: Work in progress
  
  - name: "status: review needed"
    color: fbca04
    description: Needs review
  
  - name: "status: blocked"
    color: d93f0b
    description: Blocked by something
  
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  
  - name: help wanted
    color: 008672
    description: Extra attention is needed
